"""Domain types. Lifted from prototype/src/data_scheme.py; ``Wish.mood`` and card paths added."""

from __future__ import annotations

import uuid

from pydantic import BaseModel, Field


def _new_id() -> str:
    return str(uuid.uuid4())


class KidProfile(BaseModel):
    """Profile of a child for gift recommendation."""

    id: str = Field(default_factory=_new_id)
    name: str = Field(min_length=1)
    age: int = Field(gt=0, le=18, description="Age must be between 1 and 18")
    wishlist: list[str] = Field(default_factory=list, description="What the kid wants")


class GiftRecommendation(BaseModel):
    """Gift recommendation generated by the ``llm`` role."""

    id: str = Field(default_factory=_new_id)
    kid_id: str
    gifts: list[str] = Field(min_length=1)
    rationale: str
    model_version: str


class Wish(BaseModel):
    """Personalized holiday wish generated by the ``llm`` role."""

    id: str = Field(default_factory=_new_id)
    kid_id: str
    text: str
    mood: str = Field(default="warm", description="One mood tag; picks the music track")
    model_version: str


class CardImage(BaseModel):
    """Illustration generated by the ``image`` role."""

    id: str = Field(default_factory=_new_id)
    kid_id: str
    path: str = Field(description="Local path or bucket key of the PNG")
    model_version: str
    prompt: str | None = None
    endpoint: str | None = Field(default=None, description="Base URL that produced it")

    @property
    def image_url(self) -> str:
        """Alias used by research notebooks (MLflow image logging)."""
        return self.path


class GiftCard(BaseModel):
    """Complete gift card: recommendation + wish + illustration, rendered to PNG + HTML."""

    id: str = Field(default_factory=_new_id)
    kid_id: str
    recommendation: GiftRecommendation
    wish: Wish
    image: CardImage
    png_path: str | None = None
    html_path: str | None = None
    status: str = Field(default="completed", description="pending | completed | failed")
