import uuid

from pydantic import BaseModel, Field


class KidProfile(BaseModel):
    """Profile of a child for gift recommendation."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    age: int = Field(gt=0, le=18, description="Age must be between 1 and 18")
    wishlist: list[str] = Field(default_factory=list, description="List of items the kid wants")


class GiftRecommendation(BaseModel):
    """Gift recommendation generated by LLM."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kid_id: str
    gifts: list[str] = Field(description="List of recommended gifts")
    rationale: str = Field(description="Explanation for the recommendations")
    model_version: str = Field(description="Version of the model used")


class Wish(BaseModel):
    """Personalized holiday wish generated by LLM."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kid_id: str
    text: str = Field(description="Personalized wish text")
    model_version: str = Field(description="Version of the model used")


class CardImage(BaseModel):
    """Generated card image."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kid_id: str
    image_url: str = Field(description="URL or path to the generated image")
    model_version: str = Field(description="Version of the image model used")
    prompt: str | None = Field(default=None, description="Prompt used for image generation")


class GiftCard(BaseModel):
    """Complete gift card with all components."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kid_id: str
    recommendation_id: str
    wish_id: str
    image_id: str
    rendered_url: str | None = Field(default=None, description="URL to rendered HTML/PDF card")
    status: str = Field(default="pending", description="Status: pending, completed, failed")
