"""Test samples for evaluation notebooks."""

import uuid

from pydantic import BaseModel, Field


class KidProfile(BaseModel):
    """Profile of a child for gift recommendation."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    age: int = Field(gt=0, le=18, description="Age must be between 1 and 18")
    wishlist: list[str] = Field(default_factory=list, description="List of items the kid wants")


class GiftRecommendation(BaseModel):
    """Gift recommendation generated by LLM."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kid_id: str
    gifts: list[str] = Field(description="List of recommended gifts")
    rationale: str = Field(description="Explanation for the recommendations")
    model_version: str = Field(description="Version of the model used")


class Wish(BaseModel):
    """Personalized holiday wish generated by LLM."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    kid_id: str
    text: str = Field(description="Personalized wish text")
    model_version: str = Field(description="Version of the model used")


def get_test_profiles() -> list[KidProfile]:
    """Get test kid profiles for evaluation."""
    return [
        KidProfile(name="Emma", age=7, wishlist=["doll", "art supplies", "books"]),
        KidProfile(name="Lucas", age=10, wishlist=["LEGO set", "video games", "bicycle"]),
        KidProfile(name="Sophia", age=5, wishlist=["princess dress", "stuffed animals"]),
        KidProfile(name="Noah", age=12, wishlist=["basketball", "headphones", "science kit"]),
    ]


def get_test_recommendations_for_wish() -> list[GiftRecommendation]:
    """Get test gift recommendations for wish generation evaluation."""
    profiles = get_test_profiles()
    return [
        GiftRecommendation(
            kid_id=profiles[0].id,
            gifts=["DIY doll making kit", "Watercolor painting set", "Storybook collection"],
            rationale="These gifts match Emma's creative interests.",
            model_version="test",
        ),
        GiftRecommendation(
            kid_id=profiles[1].id,
            gifts=["Advanced LEGO Technic set", "Educational coding game", "Mountain bike"],
            rationale="These gifts align with Lucas's interests in building and technology.",
            model_version="test",
        ),
        GiftRecommendation(
            kid_id=profiles[2].id,
            gifts=["Princess dress-up set", "Soft teddy bear", "Fairy tale book"],
            rationale="These gifts are perfect for Sophia's age and interests.",
            model_version="test",
        ),
        GiftRecommendation(
            kid_id=profiles[3].id,
            gifts=["Professional basketball", "Wireless headphones", "Chemistry experiment kit"],
            rationale="These gifts match Noah's active and scientific interests.",
            model_version="test",
        ),
    ]


def get_test_recommendations_for_image() -> list[GiftRecommendation]:
    """Get test gift recommendations for image generation evaluation."""
    profiles = get_test_profiles()
    return [
        GiftRecommendation(
            kid_id=profiles[0].id,
            gifts=["DIY doll making kit", "Watercolor painting set"],
            rationale="These gifts match Emma's creative interests.",
            model_version="test",
        ),
        GiftRecommendation(
            kid_id=profiles[1].id,
            gifts=["Advanced LEGO Technic set", "Mountain bike"],
            rationale="These gifts align with Lucas's interests.",
            model_version="test",
        ),
        GiftRecommendation(
            kid_id=profiles[2].id,
            gifts=["Princess dress-up set", "Soft teddy bear"],
            rationale="These gifts are perfect for Sophia.",
            model_version="test",
        ),
        GiftRecommendation(
            kid_id=profiles[3].id,
            gifts=["Professional basketball", "Chemistry experiment kit"],
            rationale="These gifts match Noah's interests.",
            model_version="test",
        ),
    ]
